# Generated by Django 5.1.4 on 2024-12-20 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulatorInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                        max_length=1,
                        verbose_name="제품 유형",
                    ),
                ),
                ("air_temperature", models.FloatField(verbose_name="공기 온도")),
                ("process_temperature", models.FloatField(verbose_name="공정 온도")),
                ("rotational_speed", models.IntegerField(verbose_name="회전 속도")),
                ("torque", models.FloatField(verbose_name="토크")),
                ("tool_wear", models.IntegerField(verbose_name="공구 마모")),
            ],
            options={
                "verbose_name": "시뮬레이터 입력값",
                "db_table": "simulator_input",
            },
        ),
        migrations.CreateModel(
            name="SimulatorOutput",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="maintenance.simulatorinput",
                        verbose_name="식별자",
                    ),
                ),
                (
                    "prediction",
                    models.IntegerField(
                        choices=[
                            (0, "No Failure"),
                            (1, "TWF"),
                            (2, "HDF"),
                            (3, "PWF"),
                            (4, "OSF"),
                        ],
                        default=0,
                        verbose_name="예측 결과값",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="결과 생성 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "시뮬레이터 출력값",
                "db_table": "simulator_output",
            },
        ),
    ]
