# Generated by Django 5.1.4 on 2024-12-31 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulatorinput",
            options={},
        ),
        migrations.AlterModelOptions(
            name="simulatoroutput",
            options={},
        ),
        migrations.RemoveField(
            model_name="simulatoroutput",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="simulatorinput",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="simulatorinput",
            name="air_temperature",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="simulatorinput",
            name="process_temperature",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="simulatorinput",
            name="rotational_speed",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="simulatorinput",
            name="tool_wear",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="simulatorinput",
            name="torque",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="simulatorinput",
            name="type",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default="L",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="simulatoroutput",
            name="id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="maintenance.simulatorinput",
            ),
        ),
        migrations.AlterField(
            model_name="simulatoroutput",
            name="prediction",
            field=models.IntegerField(
                choices=[(0, "No Failure"), (2, "HDF"), (3, "PWF"), (4, "OSF")],
                default=0,
            ),
        ),
        migrations.AlterModelTable(
            name="simulatorinput",
            table=None,
        ),
        migrations.AlterModelTable(
            name="simulatoroutput",
            table=None,
        ),
    ]
